import io
import json
from datetime import datetime
from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException
from fastapi.responses import StreamingResponse
from database import get_db
from auth import get_current_user
from models import serialize, to_object_id
from services.r2_storage import (
    upload_bytes, download_bytes, key_exists, report_key, CONTENT_TYPES
)
from logger import get_logger

logger = get_logger("routes.reports")

router = APIRouter(prefix="/api/reports", tags=["Reports"])


# ── Narrative helpers ────────────────────────────────────────────────────────

def _get_or_generate_structured(prediction: dict, db) -> dict:
    """Return the structured report dict, generating via OpenRouter if needed."""
    from services.openrouter_report import generate_narrative, parse_narrative

    raw = prediction.get("report_narrative", "")
    structured = parse_narrative(raw)

    # If we already have a rich structured report, return it
    if structured.get("summary"):
        return structured

    # Generate a new one via OpenRouter
    try:
        narrative_str = generate_narrative(
            prediction=prediction["prediction"],
            confidence=prediction["confidence"],
            signal_stats=prediction.get("signal_stats") or {},
            model_used=prediction.get("model_used") or "tabular",
            file_type=prediction.get("file_type", ""),
        )
        db["predictions"].update_one(
            {"_id": to_object_id(prediction["id"])},
            {"$set": {"report_narrative": narrative_str}},
        )
        return parse_narrative(narrative_str)
    except Exception as e:
        logger.warning(
            f"OpenRouter report generation failed for prediction {prediction.get('id')}: {e}",
            exc_info=True,
        )
        from services.openrouter_report import _static_report
        return _static_report(prediction["prediction"], prediction.get("confidence", 0.85))


def _build_report_data(prediction: dict, db) -> dict:
    structured = _get_or_generate_structured(prediction, db)
    stats = prediction.get("signal_stats") or {}

    # ── Fetch patient (user) profile ──
    from models import to_object_id as _oid
    user_doc = db["users"].find_one({"_id": _oid(prediction["user_id"])})
    patient_info = {}
    if user_doc:
        patient_info = {
            "full_name":   user_doc.get("full_name", ""),
            "father_name": user_doc.get("father_name", ""),
            "age":         user_doc.get("age", ""),
            "sex":         user_doc.get("sex", ""),
            "email":       user_doc.get("email", ""),
            "username":    user_doc.get("username", ""),
        }

    # Backwards-compat fields extracted from structured report
    interpretation_text = structured.get("clinical_interpretation") or structured.get("summary", "")
    recommendations = structured.get("recommendations") or ["Consult a qualified neurologist."]

    return {
        "report_title": "Epileptic Seizure Detection — AI Analysis Report",
        "generated_at": datetime.utcnow().isoformat(),
        # ── Patient demographics ──
        "patient_info": patient_info,
        "patient_file": {
            "filename": prediction["filename"],
            "file_type": prediction["file_type"],
            "upload_date": prediction["created_at"].isoformat()
            if hasattr(prediction.get("created_at"), "isoformat")
            else str(prediction.get("created_at", "")),
        },
        "ai_prediction": {
            "result": prediction["prediction"],
            "confidence": f"{prediction['confidence'] * 100:.1f}%",
            "confidence_value": prediction["confidence"],
            "confidence_level": structured.get("confidence_level") or (
                "Low" if prediction["confidence"] < 0.30 else
                "Moderate" if prediction["confidence"] < 0.70 else "High"
            ),
            "model_used": prediction.get("model_used") or "tabular",
        },
        "signal_analysis": {
            "num_data_points": stats.get("num_points", 0),
            "mean": f"{stats.get('mean', stats.get('mean_pixel', 0)):.4f}",
            "std": f"{stats.get('std', stats.get('std_pixel', 0)):.4f}",
            "min": f"{stats.get('min', stats.get('min_pixel', 0)):.4f}",
            "max": f"{stats.get('max', stats.get('max_pixel', 0)):.4f}",
        },
        # ── Legacy flat fields (used by PDF/DOCX + old frontend) ──
        "interpretation": {
            "pattern": interpretation_text,
            "severity": "Requires immediate medical attention"
            if prediction["prediction"] == "Seizure" else "Normal",
        },
        "recommendations": recommendations,
        "disclaimer": (
            "DISCLAIMER: This report is generated by an AI system. "
            "It is intended for informational purposes only and should not replace "
            "professional medical advice, diagnosis, or treatment."
        ),
        # ── Rich structured sections (used by new frontend UI) ──
        "detailed_report": structured,
    }


# ── R2 report cache helpers ──────────────────────────────────────────────────

def _get_or_generate_report_bytes(prediction: dict, fmt: str, report_data: dict, db) -> bytes:
    """Return report bytes — from R2 cache if available, generate+upload otherwise."""
    user_id = prediction["user_id"]
    pred_id = prediction["id"]
    r2_key = report_key(user_id, pred_id, fmt)

    try:
        if key_exists(r2_key):
            return download_bytes(r2_key)
    except Exception:
        pass

    data = _generate_bytes(fmt, report_data)

    try:
        upload_bytes(r2_key, data, CONTENT_TYPES[fmt])
        db["predictions"].update_one(
            {"_id": to_object_id(pred_id)},
            {"$set": {f"r2_reports.{fmt}": r2_key}},
        )
    except Exception as e:
        logger.warning(f"R2 report upload failed for prediction {pred_id} fmt={fmt}: {e}")

    return data


def _generate_bytes(fmt: str, report: dict) -> bytes:
    if fmt == "json":
        return json.dumps(report, indent=2).encode()
    if fmt == "pdf":
        return _generate_pdf(report)
    if fmt == "docx":
        return _generate_docx(report)
    raise ValueError(f"Unknown format: {fmt}")


def _generate_pdf(report: dict) -> bytes:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=50, bottomMargin=50,
                                leftMargin=2 * cm, rightMargin=2 * cm)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle("T", parent=styles["Title"], fontSize=20,
                                     textColor=colors.HexColor("#0077B6"), spaceAfter=4)
        subtitle_style = ParagraphStyle("Sub", parent=styles["Normal"], fontSize=10,
                                        textColor=colors.HexColor("#718096"), spaceAfter=12)
        h2_style = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13,
                                  textColor=colors.HexColor("#00B4D8"), spaceBefore=14, spaceAfter=6)
        body_style = ParagraphStyle("B", parent=styles["Normal"], fontSize=10,
                                    leading=15, textColor=colors.HexColor("#2D3748"))
        bullet_style = ParagraphStyle("Bullet", parent=body_style, leftIndent=16, spaceAfter=3)
        disclaimer_style = ParagraphStyle("Disc", parent=styles["Italic"], fontSize=8,
                                          textColor=colors.HexColor("#718096"))

        dr = report.get("detailed_report", {})
        pred = report["ai_prediction"]
        risk = dr.get("risk_assessment", {})
        risk_colors = {"Low": "#38A169", "Moderate": "#D69E2E", "High": "#E53E3E", "Critical": "#822727"}
        risk_color = risk_colors.get(risk.get("level", ""), "#718096")

        elems = []

        # Header
        elems.append(Paragraph(report["report_title"], title_style))
        elems.append(Paragraph(
            f"Generated: {report['generated_at']} UTC  •  File: {report['patient_file']['filename']}",
            subtitle_style
        ))
        elems.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0")))
        elems.append(Spacer(1, 10))

        # ── Patient Information ──────────────────────────────────────────────
        pi = report.get("patient_info", {})
        if pi and any(pi.values()):
            elems.append(Paragraph("Patient Information", h2_style))
            label_style = ParagraphStyle(
                "PLabel", parent=body_style,
                textColor=colors.HexColor("#718096"), fontSize=9
            )
            value_style = ParagraphStyle(
                "PValue", parent=body_style,
                textColor=colors.HexColor("#1A202C"), fontSize=10
            )
            pi_fields = [
                ("Full Name",    pi.get("full_name", "")),
                ("Father's Name",pi.get("father_name", "")),
                ("Age",          str(pi.get("age", ""))),
                ("Sex",          pi.get("sex", "")),
                ("Email",        pi.get("email", "")),
                ("Username",     pi.get("username", "")),
            ]
            # Build two-column rows: [Label | Value] pairs
            pi_rows = [
                [
                    Paragraph(f"{label}:", label_style),
                    Paragraph(value if value else "—", value_style),
                ]
                for label, value in pi_fields
            ]
            pi_table = Table(pi_rows, colWidths=["30%", "70%"])
            pi_table.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, -1), colors.HexColor("#F7FAFC")),
                ("ROWBACKGROUNDS",(0, 0), (-1, -1),
                 [colors.HexColor("#F7FAFC"), colors.HexColor("#EDF2F7")]),
                ("TOPPADDING",    (0, 0), (-1, -1), 7),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
                ("LEFTPADDING",   (0, 0), (-1, -1), 10),
                ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
                ("BOX",          (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E0")),
                ("INNERGRID",    (0, 0), (-1, -1), 0.25, colors.HexColor("#E2E8F0")),
            ]))
            elems.append(pi_table)
            elems.append(Spacer(1, 10))

        # AI Prediction box
        pred_color = colors.HexColor("#FED7D7") if pred["result"] == "Seizure" else colors.HexColor("#C6F6D5")
        pred_text_color = colors.HexColor("#C53030") if pred["result"] == "Seizure" else colors.HexColor("#276749")
        data = [
            [Paragraph(f"<b>AI Prediction:</b> {pred['result']}", ParagraphStyle("p", parent=body_style, textColor=pred_text_color)),
             Paragraph(f"<b>Confidence:</b> {pred['confidence']}", body_style),
             Paragraph(f"<b>Model:</b> {pred['model_used'].replace('-', ' ').title()}", body_style)],
        ]
        t = Table(data, colWidths=["40%", "30%", "30%"])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), pred_color),
            ("ROUNDEDCORNERS", [8]),
            ("TOPPADDING", (0, 0), (-1, -1), 10),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ]))
        elems.append(t)
        elems.append(Spacer(1, 8))

        # Confidence level note
        conf_level = pred.get("confidence_level", "")
        if conf_level:
            conf_colors = {"Low": "#718096", "Moderate": "#D69E2E", "High": "#38A169"}
            conf_hex = conf_colors.get(conf_level, "#718096")
            elems.append(Paragraph(
                f"<i>Model confidence: {pred['confidence']} — <font color='{conf_hex}'>{conf_level} certainty</font>. "
                "This score reflects model certainty, not clinical diagnosis probability.</i>",
                ParagraphStyle("ConfNote", parent=disclaimer_style, fontSize=9, spaceAfter=8),
            ))

        # Executive Summary
        exec_summary = dr.get("executive_summary") or dr.get("summary", "")
        if exec_summary:
            elems.append(Paragraph("Executive Summary", h2_style))
            elems.append(Paragraph(exec_summary, body_style))
            elems.append(Spacer(1, 4))

        # Risk Assessment
        if risk:
            elems.append(Paragraph("Risk Assessment", h2_style))
            elems.append(Paragraph(
                f"<b>Risk Level: <font color='{risk_color}'>{risk.get('level', 'Unknown')}</font></b> — {risk.get('rationale', '')}",
                body_style
            ))
            for f in risk.get("factors", []):
                elems.append(Paragraph(f"• {f}", bullet_style))
            elems.append(Spacer(1, 4))

        # Clinical Summary
        if dr.get("summary"):
            elems.append(Paragraph("Clinical Summary", h2_style))
            elems.append(Paragraph(dr["summary"], body_style))

        # EEG Characteristics
        if dr.get("eeg_characteristics"):
            elems.append(Paragraph("EEG Characteristics", h2_style))
            elems.append(Paragraph(dr["eeg_characteristics"], body_style))

        # Signal Statistics
        elems.append(Paragraph("Signal Statistics", h2_style))
        for k, v in report["signal_analysis"].items():
            elems.append(Paragraph(f"<b>{k.replace('_', ' ').title()}:</b> {v}", body_style))

        # Clinical Interpretation
        if dr.get("clinical_interpretation"):
            elems.append(Paragraph("Clinical Interpretation", h2_style))
            elems.append(Paragraph(dr["clinical_interpretation"], body_style))

        # Differential Diagnosis
        if dr.get("differential_diagnosis"):
            elems.append(Paragraph("Differential Diagnosis", h2_style))
            for d in dr["differential_diagnosis"]:
                elems.append(Paragraph(f"• {d}", bullet_style))

        # Immediate Actions
        if dr.get("immediate_actions"):
            elems.append(Paragraph("Immediate Actions", h2_style))
            for a in dr["immediate_actions"]:
                elems.append(Paragraph(f"• {a}", bullet_style))

        # Recommendations
        elems.append(Paragraph("Recommendations", h2_style))
        for rec in report["recommendations"]:
            elems.append(Paragraph(f"• {rec}", bullet_style))

        # Follow-Up Plan
        if dr.get("follow_up_plan"):
            elems.append(Paragraph("Follow-Up Plan", h2_style))
            elems.append(Paragraph(dr["follow_up_plan"], body_style))

        # Lifestyle Guidance
        if dr.get("lifestyle_guidance"):
            elems.append(Paragraph("Lifestyle Guidance", h2_style))
            for tip in dr["lifestyle_guidance"]:
                elems.append(Paragraph(f"• {tip}", bullet_style))

        # Disclaimer
        elems.append(Spacer(1, 16))
        elems.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E2E8F0")))
        elems.append(Spacer(1, 6))
        elems.append(Paragraph(report["disclaimer"], disclaimer_style))

        doc.build(elems)
        return buf.getvalue()
    except ImportError:
        raise HTTPException(500, "reportlab not installed")


def _generate_docx(report: dict) -> bytes:
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH

        doc = Document()
        dr = report.get("detailed_report", {})
        pred = report["ai_prediction"]
        risk = dr.get("risk_assessment", {})

        # Title
        title = doc.add_heading(report["report_title"], level=0)
        title.runs[0].font.color.rgb = RGBColor(0, 119, 182)

        doc.add_paragraph(
            f"Generated: {report['generated_at']}  |  File: {report['patient_file']['filename']}"
        ).runs[0].font.color.rgb = RGBColor(113, 128, 150)

        # Prediction
        doc.add_heading("AI Prediction", level=1)
        p = doc.add_paragraph()
        r = p.add_run(f"Result: {pred['result']}")
        r.bold = True
        r.font.color.rgb = RGBColor(197, 48, 48) if pred["result"] == "Seizure" else RGBColor(39, 103, 73)
        doc.add_paragraph(f"Confidence: {pred['confidence']} ({pred.get('confidence_level', '')} certainty)")
        doc.add_paragraph(f"Model: {pred['model_used'].replace('-', ' ').title()}")
        note = doc.add_paragraph("Note: Confidence score reflects model certainty, not clinical diagnosis probability.")
        note.runs[0].italic = True
        note.runs[0].font.color.rgb = RGBColor(113, 128, 150)

        # Executive Summary
        exec_summary = dr.get("executive_summary") or dr.get("summary", "")
        if exec_summary:
            doc.add_heading("Executive Summary", level=1)
            doc.add_paragraph(exec_summary)

        # Risk Assessment
        if risk:
            doc.add_heading("Risk Assessment", level=1)
            rp = doc.add_paragraph()
            rp.add_run(f"Risk Level: {risk.get('level', 'Unknown')}").bold = True
            doc.add_paragraph(risk.get("rationale", ""))
            for f in risk.get("factors", []):
                doc.add_paragraph(f, style="List Bullet")

        # Summary
        if dr.get("summary"):
            doc.add_heading("Clinical Summary", level=1)
            doc.add_paragraph(dr["summary"])

        # EEG Characteristics
        if dr.get("eeg_characteristics"):
            doc.add_heading("EEG Characteristics", level=1)
            doc.add_paragraph(dr["eeg_characteristics"])

        # Signal Analysis
        doc.add_heading("Signal Statistics", level=1)
        for k, v in report["signal_analysis"].items():
            doc.add_paragraph(f"{k.replace('_', ' ').title()}: {v}")

        # Clinical Interpretation
        if dr.get("clinical_interpretation"):
            doc.add_heading("Clinical Interpretation", level=1)
            doc.add_paragraph(dr["clinical_interpretation"])

        # Differential Diagnosis
        if dr.get("differential_diagnosis"):
            doc.add_heading("Differential Diagnosis", level=1)
            for d in dr["differential_diagnosis"]:
                doc.add_paragraph(d, style="List Bullet")

        # Immediate Actions
        if dr.get("immediate_actions"):
            doc.add_heading("Immediate Actions", level=1)
            for a in dr["immediate_actions"]:
                doc.add_paragraph(a, style="List Bullet")

        # Recommendations
        doc.add_heading("Recommendations", level=1)
        for rec in report["recommendations"]:
            doc.add_paragraph(rec, style="List Bullet")

        # Follow-Up Plan
        if dr.get("follow_up_plan"):
            doc.add_heading("Follow-Up Plan", level=1)
            doc.add_paragraph(dr["follow_up_plan"])

        # Lifestyle Guidance
        if dr.get("lifestyle_guidance"):
            doc.add_heading("Lifestyle Guidance", level=1)
            for tip in dr["lifestyle_guidance"]:
                doc.add_paragraph(tip, style="List Bullet")

        # Disclaimer
        doc.add_heading("Disclaimer", level=1)
        disc = doc.add_paragraph(report["disclaimer"])
        disc.runs[0].italic = True
        disc.runs[0].font.color.rgb = RGBColor(113, 128, 150)

        buf = io.BytesIO()
        doc.save(buf)
        return buf.getvalue()
    except ImportError:
        raise HTTPException(500, "python-docx not installed")


# ── Routes ───────────────────────────────────────────────────────────────────

def _get_prediction_or_404(prediction_id: str, user_id: str, db):
    oid = to_object_id(prediction_id)
    if not oid:
        raise HTTPException(404, "Invalid prediction ID")
    doc = db["predictions"].find_one({"_id": oid, "user_id": user_id})
    if not doc:
        raise HTTPException(404, "Prediction not found")
    return serialize(doc)


@router.get("/{prediction_id}")
def get_report(
    prediction_id: str,
    background_tasks: BackgroundTasks,
    current_user: dict = Depends(get_current_user),
):
    db = get_db()
    prediction = _get_prediction_or_404(prediction_id, current_user["id"], db)
    report_data = _build_report_data(prediction, db)

    # Send report email exactly once — atomic update guards against concurrent requests
    if not prediction.get("email_sent"):
        try:
            claim = db["predictions"].update_one(
                {"_id": to_object_id(prediction_id), "email_sent": {"$ne": True}},
                {"$set": {"email_sent": True}},
            )
            if claim.modified_count > 0:
                from services.email_service import send_report_email
                # Generate PDF to attach — best-effort, never blocks the response
                pdf_bytes = None
                try:
                    pdf_bytes = _get_or_generate_report_bytes(prediction, "pdf", report_data, db)
                except Exception as pdf_err:
                    logger.warning(f"PDF generation for email attachment failed: {pdf_err}")
                background_tasks.add_task(
                    send_report_email, prediction, report_data, current_user, pdf_bytes
                )
        except Exception as e:
            logger.warning(f"Could not claim email_sent for {prediction_id}: {e}")

    return report_data


@router.get("/{prediction_id}/download/{fmt}")
def download_report(
    prediction_id: str,
    fmt: str,
    current_user: dict = Depends(get_current_user),
):
    if fmt not in ("pdf", "docx", "json"):
        raise HTTPException(400, f"Unsupported format '{fmt}'. Use pdf, docx, or json.")

    db = get_db()
    prediction = _get_prediction_or_404(prediction_id, current_user["id"], db)
    logger.info(
        f"Report download requested: prediction={prediction_id} fmt={fmt}",
        extra={"user_id": current_user["id"]},
    )
    report_data = _build_report_data(prediction, db)

    # PDF / DOCX always regenerated fresh so patient profile updates are reflected.
    # JSON can still be served from R2 cache.
    if fmt == "json":
        data = _get_or_generate_report_bytes(prediction, fmt, report_data, db)
    else:
        data = _generate_bytes(fmt, report_data)

    return StreamingResponse(
        io.BytesIO(data),
        media_type=CONTENT_TYPES[fmt],
        headers={"Content-Disposition": f"attachment; filename=seizure_report_{prediction_id}.{fmt}"},
    )
